// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFS)
	t.Run("SchemaMigrations", testSchemaMigrations)
	t.Run("Users", testUsers)
	t.Run("UsersPDFS", testUsersPDFS)
}

func TestDelete(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSDelete)
	t.Run("SchemaMigrations", testSchemaMigrationsDelete)
	t.Run("Users", testUsersDelete)
	t.Run("UsersPDFS", testUsersPDFSDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSQueryDeleteAll)
	t.Run("SchemaMigrations", testSchemaMigrationsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
	t.Run("UsersPDFS", testUsersPDFSQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSSliceDeleteAll)
	t.Run("SchemaMigrations", testSchemaMigrationsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
	t.Run("UsersPDFS", testUsersPDFSSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSExists)
	t.Run("SchemaMigrations", testSchemaMigrationsExists)
	t.Run("Users", testUsersExists)
	t.Run("UsersPDFS", testUsersPDFSExists)
}

func TestFind(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSFind)
	t.Run("SchemaMigrations", testSchemaMigrationsFind)
	t.Run("Users", testUsersFind)
	t.Run("UsersPDFS", testUsersPDFSFind)
}

func TestBind(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSBind)
	t.Run("SchemaMigrations", testSchemaMigrationsBind)
	t.Run("Users", testUsersBind)
	t.Run("UsersPDFS", testUsersPDFSBind)
}

func TestOne(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSOne)
	t.Run("SchemaMigrations", testSchemaMigrationsOne)
	t.Run("Users", testUsersOne)
	t.Run("UsersPDFS", testUsersPDFSOne)
}

func TestAll(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSAll)
	t.Run("SchemaMigrations", testSchemaMigrationsAll)
	t.Run("Users", testUsersAll)
	t.Run("UsersPDFS", testUsersPDFSAll)
}

func TestCount(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSCount)
	t.Run("SchemaMigrations", testSchemaMigrationsCount)
	t.Run("Users", testUsersCount)
	t.Run("UsersPDFS", testUsersPDFSCount)
}

func TestHooks(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSHooks)
	t.Run("SchemaMigrations", testSchemaMigrationsHooks)
	t.Run("Users", testUsersHooks)
	t.Run("UsersPDFS", testUsersPDFSHooks)
}

func TestInsert(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSInsert)
	t.Run("PartialPDFS", testPartialPDFSInsertWhitelist)
	t.Run("SchemaMigrations", testSchemaMigrationsInsert)
	t.Run("SchemaMigrations", testSchemaMigrationsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
	t.Run("UsersPDFS", testUsersPDFSInsert)
	t.Run("UsersPDFS", testUsersPDFSInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("PartialPDFToUsersPDFUsingUnifiedPDF", testPartialPDFToOneUsersPDFUsingUnifiedPDF)
	t.Run("UsersPDFToUserUsingUser", testUsersPDFToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("UserToUsersPDFS", testUserToManyUsersPDFS)
	t.Run("UsersPDFToUnifiedPDFPartialPDFS", testUsersPDFToManyUnifiedPDFPartialPDFS)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("PartialPDFToUsersPDFUsingUnifiedPDFPartialPDFS", testPartialPDFToOneSetOpUsersPDFUsingUnifiedPDF)
	t.Run("UsersPDFToUserUsingUsersPDFS", testUsersPDFToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("PartialPDFToUsersPDFUsingUnifiedPDFPartialPDFS", testPartialPDFToOneRemoveOpUsersPDFUsingUnifiedPDF)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("UserToUsersPDFS", testUserToManyAddOpUsersPDFS)
	t.Run("UsersPDFToUnifiedPDFPartialPDFS", testUsersPDFToManyAddOpUnifiedPDFPartialPDFS)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("UsersPDFToUnifiedPDFPartialPDFS", testUsersPDFToManySetOpUnifiedPDFPartialPDFS)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("UsersPDFToUnifiedPDFPartialPDFS", testUsersPDFToManyRemoveOpUnifiedPDFPartialPDFS)
}

func TestReload(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSReload)
	t.Run("SchemaMigrations", testSchemaMigrationsReload)
	t.Run("Users", testUsersReload)
	t.Run("UsersPDFS", testUsersPDFSReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSReloadAll)
	t.Run("SchemaMigrations", testSchemaMigrationsReloadAll)
	t.Run("Users", testUsersReloadAll)
	t.Run("UsersPDFS", testUsersPDFSReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSSelect)
	t.Run("SchemaMigrations", testSchemaMigrationsSelect)
	t.Run("Users", testUsersSelect)
	t.Run("UsersPDFS", testUsersPDFSSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSUpdate)
	t.Run("SchemaMigrations", testSchemaMigrationsUpdate)
	t.Run("Users", testUsersUpdate)
	t.Run("UsersPDFS", testUsersPDFSUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("PartialPDFS", testPartialPDFSSliceUpdateAll)
	t.Run("SchemaMigrations", testSchemaMigrationsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
	t.Run("UsersPDFS", testUsersPDFSSliceUpdateAll)
}
